version: "3.9"

services:
  app:
    image: mercari-build-training/app:latest
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - FRONT_URL=http://localhost:3000

  web:
    image: mercari-build-training/web:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:9000
    depends_on:
      - app

